config/routes.rb
ShareAllTech::Application.routes.draw do

  root :to => 'posts#index'

  resources :posts do
    resources :comments
    resources :likes, :only => [:create, :destroy]
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

  get 'info/aboutus'
  get 'info/projects'
  get 'info/spider'

  devise_for :users

  match '/auth/:provider/callback' => 'sessions#create', :as => :oauth_callback
  match '/auth/failure' => 'sessions#failure'
  match '/logout' => 'sessions#destroy', :as => :logout

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin', :only => [:admin?]

end

app/views/common/_ads.html.erb
<section class="widget">
  <div class="wrapper">
    <h3 class="widget-title">Advertisement</h3>
    <div id="latestwork-sidebar" class="carousel slide">
        <div class="carousel-inner">
          <div class="active item"><%= image_tag("bruce.jpg")%></div>
          <div class="item"><%= image_tag("team3.jpg")%></div>
          <div class="item"><%= image_tag("team2.jpg")%></div>
          <div class="item"><%= image_tag("team4.jpg")%></div>
        </div>
        <a class="carousel-control left" href="#latestwork-sidebar" data-slide="prev"></a>
        <a class="carousel-control right" href="#latestwork-sidebar" data-slide="next"></a>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
        $('.carousel').carousel({
            interval: 5000
        })
    });
  </script>
</section>

app/views/common/_footer.html.erb
<footer id="footer">
  <div class="wrapper">
    <section id="footer-menu">
      <div class="row-fluid">
        <div class="8">
          <p class="copyright">&copy; Copyright <%= Time.now.year %> - ShareAllTech. Powered by <a href="#">Bruce Yue.</a>
            <i class="iconm-mobile-2"></i> (+86)1893164XXXX &nbsp;
            <i class="iconm-mail-3"></i> <a href="mailto:#">bruce.yue@outlook.com</a>
          </p>
        </div>
      </div>
    </section>
    <!-- end: Footer Menu -->
  </div>
</footer>

app/views/common/_ga.html.erb
<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38763296-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/common/_header.html.erb
<head>
	<title>ShareAllTech</title>
	<%= stylesheet_link_tag    :application %>
	<%= javascript_include_tag :application %>
	<%= csrf_meta_tags %>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="viewport" content="width=100%, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"/>
	<meta name="keywords" content="ruby, rails, ruby on rails, github, web design and development, salesforce, apex code, visualforce, force.com, database.com" />
	<%= favicon_link_tag '/favicon.ico' %>
</head>

app/views/common/_latest_post.html.erb
<% if Post.order('created_at DESC').size != 0 %>
  <section class="widget popular-posts">
    <div class="wrapper">
      <h3 class="widget-title">Popular Tech</h3>
      <% Post.order('created_at DESC').limit(5).each do |post| %>
        <div class="media">
          <a class="pull-left" href="#">
            <% if (post.user && post.user.email) %>
              <%= gravatar_image_tag post.user.email, alt: post.user.name %>
            <% else %>
              <%= image_tag('df.png', height: 55, width: 55)%>
            <% end %>
            <span class="frame-overlay"></span>
          </a>
          <div class="media-body">
            <h4 class="media-heading"><%= link_to post.title, post %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

app/views/common/_login_form.html.erb
<% if !user_signed_in? %>
  <li>
    <%= form_tag("/auth/salesforce", id: "loginForm", style: "height:5px") do %>
      <a href="javascript:{}" onclick="document.getElementById('loginForm').submit()" >Login with Salesforce</a>
    <% end %>
  </li>
<% else %>
	<li><i class="icon-user"></i><%= current_user.name %></li>
	<li><a href="/logout">&nbsp;<i class="icon-off"></i>Logout</a></li>
<% end %>

app/views/common/_menu.html.erb
<header id="header">
  <!-- start: Main menu -->
  <div class="container">
    <nav id="menu" class="clearfix">
      <ul>
        <li><%= link_to "Home", posts_path %></li>
        <li><%= link_to "New Tech", new_post_path %></li>
        <li><%= link_to "About Us", info_aboutus_path %></li>
        <li><%= link_to "Projects", info_projects_path %></li>
        <li><%= link_to "Spider", info_spider_path %></li>
        <li><a href="#">Development</a>
          <ul>
            <li><a href="#">Salesforce</a>
              <ul>
                <li><a href="#">Apex Code</a></li>
                <li><a href="#">Visualforce</a></li>
                <li><a href="#">Heroku</a></li>
              </ul>
            </li>
            <li><a href="#">Ruby on Rails</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  <!-- end: Main menu -->
</header>

app/views/common/_recent_years.html.erb
<!-- Widget -->
<% if @post_month %>
  <section class="widget">
    <div class="wrapper">
      <h3 class="widget-title">Archives</h3>
      <div class="accordion" id="accordion2">
        <% @post_month.sort.reverse.each do |month, posts| %>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= month.strftime('%B%Y') %>" >
                <i class="iconm-plus-3"></i>
                <%= month.strftime('%B %Y') %> (<%= posts.count %>)
              </a>
            </div>
            <div id="collapse<%= month.strftime('%B%Y')%>" class="accordion-body collapse">
              <div class="accordion-inner">
                <ul class="the-icons">
                  <% for post in posts %>
                    <li><i class="iconm-link-3"></i><%= link_to post.title,  post %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/common/_search_form.html.erb
<section class="widget search">
  <div class="wrapper clearfix">
	  <form id="search" action="/posts" method="get">
	    <input type="text" name="search" value="<%= params[:search] %>" placeholder="Search" style="margin-bottom: 0; padding-left: 0; padding-right: 0;"/>
	  </form>
  </div>
</section>

app/views/common/_social.html.erb
<section id="top-menu">
  <div class="container">
    <div class="row">
      <div class="span4 logo">
        <a class="logo-img" href="https://www.sharealltech.com" target="_blank" ><%= image_tag("sat.png")%></a>
      </div>
      <div class="span8">
        <ul class="top-social hidden-phone">
          <%= render "common/login_form" %>
          <li><a href="http://www.facebook.com/bruce.yue" rel="tooltip" data-placement="bottom" data-original-title="Facebook"><i class="icon-facebook"></i></a></li>
          <li><a href="https://twitter.com/bruceyue" rel="tooltip" data-placement="bottom" data-original-title="Twitter"><i class="icon-twitter"></i></a></li>
          <li><a href="http://www.linkedin.com/pub/bruce-yue/42/959/978" rel="tooltip" data-placement="bottom" data-original-title="LinkedIn"><i class="icon-linkedin"></i></a></li>
          <li><a href="http://weibo.com/u/1043790213" rel="tooltip" data-placement="bottom" data-original-title="Weibo"><i class="icon-pinterest"></i></a></li>
          <li><a href="https://plus.google.com/109788557844914128707" rel="tooltip" data-placement="bottom" data-original-title="Google+"><i class="icon-google-plus last"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/common/_social_network.html.erb
<aside class="widget widget_connect">
  	<h4 class="widget-title">Get Connected</h4>
  	<nav>
		<iframe src="http://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.sharealltech.com%2F&send=false&layout=standard&width=400&show_faces=true&font=arial&colorscheme=light&action=like&height=80" allowTransparency="true"></iframe>
	</nav>
</aside>

app/views/common/_tags.html.erb
<section class="widget">
  <div class="wrapper">
    <h3 class="widget-title">Tag Cloud</h3>
    <div class="tags">
    	<% tag_cloud Post.tag_counts.uniq do |tag| %>
        <a href="<%= tag_path(tag.name) %>"><i class="icon-tag"></i><%= tag.name %></a>
      <%end%>
    </div>
  </div>
</section>